/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Request object for DLP text detection with 23 PII detection types.
type DlpDetectionRequest struct {
	// Text to scan for PII and sensitive data.
	InputText string `json:"InputText,omitempty"`
	// Set to true to allow email addresses in the input text and not flag them as PII.
	AllowEmailAddress bool `json:"AllowEmailAddress,omitempty"`
	// Set to true to allow phone numbers in the input text and not flag them as PII.
	AllowPhoneNumber bool `json:"AllowPhoneNumber,omitempty"`
	// Set to true to allow street addresses in the input text and not flag them as PII.
	AllowStreetAddress bool `json:"AllowStreetAddress,omitempty"`
	// Set to true to allow person names in the input text and not flag them as PII.
	AllowPersonName bool `json:"AllowPersonName,omitempty"`
	// Set to true to allow birth dates in the input text and not flag them as PII.
	AllowBirthDate bool `json:"AllowBirthDate,omitempty"`
	// Set to true to allow passport numbers in the input text and not flag them as PII.
	AllowPassportNumber bool `json:"AllowPassportNumber,omitempty"`
	// Set to true to allow drivers license numbers in the input text and not flag them as PII.
	AllowDriversLicense bool `json:"AllowDriversLicense,omitempty"`
	// Set to true to allow social security numbers in the input text and not flag them as PII.
	AllowSocialSecurityNumber bool `json:"AllowSocialSecurityNumber,omitempty"`
	// Set to true to allow taxpayer IDs in the input text and not flag them as PII.
	AllowTaxpayerID bool `json:"AllowTaxpayerID,omitempty"`
	// Set to true to allow credit card numbers in the input text and not flag them as PII.
	AllowCreditCardNumber bool `json:"AllowCreditCardNumber,omitempty"`
	// Set to true to allow credit card expiration dates in the input text and not flag them as PII.
	AllowCreditCardExpirationDate bool `json:"AllowCreditCardExpirationDate,omitempty"`
	// Set to true to allow credit card verification codes in the input text and not flag them as PII.
	AllowCreditCardVerificationCode bool `json:"AllowCreditCardVerificationCode,omitempty"`
	// Set to true to allow bank account numbers in the input text and not flag them as PII.
	AllowBankAccountNumber bool `json:"AllowBankAccountNumber,omitempty"`
	// Set to true to allow IBANs in the input text and not flag them as PII.
	AllowIBAN bool `json:"AllowIBAN,omitempty"`
	// Set to true to allow health insurance numbers in the input text and not flag them as PII.
	AllowHealthInsuranceNumber bool `json:"AllowHealthInsuranceNumber,omitempty"`
	// Set to true to allow bearer tokens in the input text and not flag them as PII.
	AllowBearerToken bool `json:"AllowBearerToken,omitempty"`
	// Set to true to allow HTTP cookies in the input text and not flag them as PII.
	AllowHttpCookie bool `json:"AllowHttpCookie,omitempty"`
	// Set to true to allow private keys in the input text and not flag them as PII.
	AllowPrivateKeys bool `json:"AllowPrivateKeys,omitempty"`
	// Set to true to allow credentials (usernames/passwords) in the input text and not flag them as PII.
	AllowCredentials bool `json:"AllowCredentials,omitempty"`
	// Set to true to allow deep web URLs (.onion) in the input text and not flag them as PII.
	AllowDeepWebUrls bool `json:"AllowDeepWebUrls,omitempty"`
	// Set to true to allow source code in the input text and not flag it as sensitive data.
	AllowSourceCode bool `json:"AllowSourceCode,omitempty"`
	// Set to true to allow IP addresses in the input text and not flag them as PII.
	AllowIpAddress bool `json:"AllowIpAddress,omitempty"`
	// Set to true to allow MAC addresses in the input text and not flag them as PII.
	AllowMacAddress bool `json:"AllowMacAddress,omitempty"`
}
