/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Request object for advanced DLP document redaction with 35 PII detection types including health-related data.
type DlpAdvancedDocumentRedactionRequest struct {
	// Document file bytes (PDF, DOCX, PNG, or JPG) to scan for PII and redact.
	InputFile string `json:"InputFile,omitempty"`
	// Optional. Name of the input file including extension, used for format detection. If not provided, format is detected from file contents.
	FileName string `json:"FileName,omitempty"`
	// Optional. Recognition mode for image processing. Options: null (default), \"Fast\", \"FastPlus\", \"FastMini\".
	RecognitionMode string `json:"RecognitionMode,omitempty"`
	// Redaction mode for PII regions. Options: \"BlackOut\" (default) draws black rectangles over PII rows, \"Blur\" applies Gaussian blur to PII rows, \"BlackOutEntirePage\" blacks out entire dirty pages, \"BlurEntirePage\" blurs entire dirty pages.
	RedactionMode string `json:"RedactionMode,omitempty"`
	// Set to true to allow email addresses in the document and not redact them.
	AllowEmailAddress bool `json:"AllowEmailAddress,omitempty"`
	// Set to true to allow phone numbers in the document and not redact them.
	AllowPhoneNumber bool `json:"AllowPhoneNumber,omitempty"`
	// Set to true to allow street addresses in the document and not redact them.
	AllowStreetAddress bool `json:"AllowStreetAddress,omitempty"`
	// Set to true to allow person names in the document and not redact them.
	AllowPersonName bool `json:"AllowPersonName,omitempty"`
	// Set to true to allow birth dates in the document and not redact them.
	AllowBirthDate bool `json:"AllowBirthDate,omitempty"`
	// Set to true to allow passport numbers in the document and not redact them.
	AllowPassportNumber bool `json:"AllowPassportNumber,omitempty"`
	// Set to true to allow drivers license numbers in the document and not redact them.
	AllowDriversLicense bool `json:"AllowDriversLicense,omitempty"`
	// Set to true to allow social security numbers in the document and not redact them.
	AllowSocialSecurityNumber bool `json:"AllowSocialSecurityNumber,omitempty"`
	// Set to true to allow taxpayer IDs in the document and not redact them.
	AllowTaxpayerID bool `json:"AllowTaxpayerID,omitempty"`
	// Set to true to allow credit card numbers in the document and not redact them.
	AllowCreditCardNumber bool `json:"AllowCreditCardNumber,omitempty"`
	// Set to true to allow credit card expiration dates in the document and not redact them.
	AllowCreditCardExpirationDate bool `json:"AllowCreditCardExpirationDate,omitempty"`
	// Set to true to allow credit card verification codes in the document and not redact them.
	AllowCreditCardVerificationCode bool `json:"AllowCreditCardVerificationCode,omitempty"`
	// Set to true to allow bank account numbers in the document and not redact them.
	AllowBankAccountNumber bool `json:"AllowBankAccountNumber,omitempty"`
	// Set to true to allow IBANs in the document and not redact them.
	AllowIBAN bool `json:"AllowIBAN,omitempty"`
	// Set to true to allow health insurance numbers in the document and not redact them.
	AllowHealthInsuranceNumber bool `json:"AllowHealthInsuranceNumber,omitempty"`
	// Set to true to allow bearer tokens in the document and not redact them.
	AllowBearerToken bool `json:"AllowBearerToken,omitempty"`
	// Set to true to allow HTTP cookies in the document and not redact them.
	AllowHttpCookie bool `json:"AllowHttpCookie,omitempty"`
	// Set to true to allow private keys in the document and not redact them.
	AllowPrivateKeys bool `json:"AllowPrivateKeys,omitempty"`
	// Set to true to allow credentials (usernames/passwords) in the document and not redact them.
	AllowCredentials bool `json:"AllowCredentials,omitempty"`
	// Set to true to allow deep web URLs (.onion) in the document and not redact them.
	AllowDeepWebUrls bool `json:"AllowDeepWebUrls,omitempty"`
	// Set to true to allow source code in the document and not redact it.
	AllowSourceCode bool `json:"AllowSourceCode,omitempty"`
	// Set to true to allow IP addresses in the document and not redact them.
	AllowIpAddress bool `json:"AllowIpAddress,omitempty"`
	// Set to true to allow MAC addresses in the document and not redact them.
	AllowMacAddress bool `json:"AllowMacAddress,omitempty"`
	// Set to true to allow health insurance member IDs in the document and not redact them.
	AllowHealthInsuranceMemberID bool `json:"AllowHealthInsuranceMemberID,omitempty"`
	// Set to true to allow references to injuries or diseases in the document and not redact them.
	AllowHealthInjuryOrDisease bool `json:"AllowHealthInjuryOrDisease,omitempty"`
	// Set to true to allow references to types of medical treatment in the document and not redact them.
	AllowHealthTypeOfTreatment bool `json:"AllowHealthTypeOfTreatment,omitempty"`
	// Set to true to allow dates and times of medical treatment in the document and not redact them.
	AllowHealthDateAndTimeOfTreatment bool `json:"AllowHealthDateAndTimeOfTreatment,omitempty"`
	// Set to true to allow health plan beneficiary numbers in the document and not redact them.
	AllowHealthPlanBeneficiaryNumber bool `json:"AllowHealthPlanBeneficiaryNumber,omitempty"`
	// Set to true to allow payments made for medical treatment in the document and not redact them.
	AllowHealthPaymentsMadeForTreatment bool `json:"AllowHealthPaymentsMadeForTreatment,omitempty"`
	// Set to true to allow identifiable human faces in the document and not redact them.
	AllowFaces bool `json:"AllowFaces,omitempty"`
	// Set to true to allow vehicle identifiers (e.g. license plates, VINs) in the document and not redact them.
	AllowVehicleID bool `json:"AllowVehicleID,omitempty"`
	// Set to true to allow device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs) in the document and not redact them.
	AllowDeviceID bool `json:"AllowDeviceID,omitempty"`
	// Set to true to allow names of relatives in the document and not redact them.
	AllowNamesOfRelatives bool `json:"AllowNamesOfRelatives,omitempty"`
	// Set to true to allow health universal record locators (URLs) in the document and not redact them.
	AllowHealthUniversalRecordLocator bool `json:"AllowHealthUniversalRecordLocator,omitempty"`
	// Set to true to allow biometric data references (e.g. fingerprints, retinal scans, voiceprints) in the document and not redact them.
	AllowBiometrics bool `json:"AllowBiometrics,omitempty"`
	// Set to true to include a natural language rationale explaining why each detection conclusion was formed.
	ProvideAnalysisRationale bool `json:"ProvideAnalysisRationale,omitempty"`
}
