/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Response object for advanced DLP document redaction with 35 PII detection results, redacted document, and optional rationale.
type DlpAdvancedDocumentRedactionResponse struct {
	// The redacted document as a rasterized PDF with PII regions redacted, or the original file if no disallowed PII was found.
	RedactedDocument string `json:"RedactedDocument,omitempty"`
	// True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.
	CleanResult bool `json:"CleanResult,omitempty"`
	// True if the document contains email addresses.
	ContainsEmailAddress bool `json:"ContainsEmailAddress,omitempty"`
	// True if the document contains phone numbers.
	ContainsPhoneNumber bool `json:"ContainsPhoneNumber,omitempty"`
	// True if the document contains street addresses.
	ContainsStreetAddress bool `json:"ContainsStreetAddress,omitempty"`
	// True if the document contains person names.
	ContainsPersonName bool `json:"ContainsPersonName,omitempty"`
	// True if the document contains birth dates.
	ContainsBirthDate bool `json:"ContainsBirthDate,omitempty"`
	// True if the document contains passport numbers.
	ContainsPassportNumber bool `json:"ContainsPassportNumber,omitempty"`
	// True if the document contains drivers license numbers.
	ContainsDriversLicense bool `json:"ContainsDriversLicense,omitempty"`
	// True if the document contains social security numbers.
	ContainsSocialSecurityNumber bool `json:"ContainsSocialSecurityNumber,omitempty"`
	// True if the document contains taxpayer IDs.
	ContainsTaxpayerID bool `json:"ContainsTaxpayerID,omitempty"`
	// True if the document contains credit card numbers.
	ContainsCreditCardNumber bool `json:"ContainsCreditCardNumber,omitempty"`
	// True if the document contains credit card expiration dates.
	ContainsCreditCardExpirationDate bool `json:"ContainsCreditCardExpirationDate,omitempty"`
	// True if the document contains credit card verification codes.
	ContainsCreditCardVerificationCode bool `json:"ContainsCreditCardVerificationCode,omitempty"`
	// True if the document contains bank account numbers.
	ContainsBankAccountNumber bool `json:"ContainsBankAccountNumber,omitempty"`
	// True if the document contains IBANs.
	ContainsIBAN bool `json:"ContainsIBAN,omitempty"`
	// True if the document contains health insurance numbers.
	ContainsHealthInsuranceNumber bool `json:"ContainsHealthInsuranceNumber,omitempty"`
	// True if the document contains bearer tokens.
	ContainsBearerToken bool `json:"ContainsBearerToken,omitempty"`
	// True if the document contains HTTP cookies.
	ContainsHttpCookie bool `json:"ContainsHttpCookie,omitempty"`
	// True if the document contains private keys.
	ContainsPrivateKeys bool `json:"ContainsPrivateKeys,omitempty"`
	// True if the document contains credentials (usernames/passwords).
	ContainsCredentials bool `json:"ContainsCredentials,omitempty"`
	// True if the document contains deep web URLs (.onion).
	ContainsDeepWebUrls bool `json:"ContainsDeepWebUrls,omitempty"`
	// True if the document contains source code.
	ContainsSourceCode bool `json:"ContainsSourceCode,omitempty"`
	// True if the document contains IP addresses.
	ContainsIpAddress bool `json:"ContainsIpAddress,omitempty"`
	// True if the document contains MAC addresses.
	ContainsMacAddress bool `json:"ContainsMacAddress,omitempty"`
	// True if the document contains health insurance member IDs.
	ContainsHealthInsuranceMemberID bool `json:"ContainsHealthInsuranceMemberID,omitempty"`
	// True if the document contains references to injuries or diseases.
	ContainsHealthInjuryOrDisease bool `json:"ContainsHealthInjuryOrDisease,omitempty"`
	// True if the document contains references to types of medical treatment.
	ContainsHealthTypeOfTreatment bool `json:"ContainsHealthTypeOfTreatment,omitempty"`
	// True if the document contains dates and times of medical treatment.
	ContainsHealthDateAndTimeOfTreatment bool `json:"ContainsHealthDateAndTimeOfTreatment,omitempty"`
	// True if the document contains health plan beneficiary numbers.
	ContainsHealthPlanBeneficiaryNumber bool `json:"ContainsHealthPlanBeneficiaryNumber,omitempty"`
	// True if the document contains payments made for medical treatment.
	ContainsHealthPaymentsMadeForTreatment bool `json:"ContainsHealthPaymentsMadeForTreatment,omitempty"`
	// True if the document contains identifiable human faces.
	ContainsFaces bool `json:"ContainsFaces,omitempty"`
	// True if the document contains vehicle identifiers (e.g. license plates, VINs).
	ContainsVehicleID bool `json:"ContainsVehicleID,omitempty"`
	// True if the document contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).
	ContainsDeviceID bool `json:"ContainsDeviceID,omitempty"`
	// True if the document contains names of relatives.
	ContainsNamesOfRelatives bool `json:"ContainsNamesOfRelatives,omitempty"`
	// True if the document contains health universal record locators (URLs).
	ContainsHealthUniversalRecordLocator bool `json:"ContainsHealthUniversalRecordLocator,omitempty"`
	// True if the document contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).
	ContainsBiometrics bool `json:"ContainsBiometrics,omitempty"`
	// List of pages that were redacted (had PII regions redacted).
	PagesRedacted []RedactedPageInfo `json:"PagesRedacted,omitempty"`
	// Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.
	AnalysisRationale string `json:"AnalysisRationale,omitempty"`
}
