/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Response object for DLP document redaction with 23 PII detection results and redacted document.
type DlpDocumentRedactionResponse struct {
	// The redacted document as a rasterized PDF with PII regions blurred, or the original file if no disallowed PII was found.
	RedactedDocument string `json:"RedactedDocument,omitempty"`
	// True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.
	CleanResult bool `json:"CleanResult,omitempty"`
	// True if the document contains email addresses.
	ContainsEmailAddress bool `json:"ContainsEmailAddress,omitempty"`
	// True if the document contains phone numbers.
	ContainsPhoneNumber bool `json:"ContainsPhoneNumber,omitempty"`
	// True if the document contains street addresses.
	ContainsStreetAddress bool `json:"ContainsStreetAddress,omitempty"`
	// True if the document contains person names.
	ContainsPersonName bool `json:"ContainsPersonName,omitempty"`
	// True if the document contains birth dates.
	ContainsBirthDate bool `json:"ContainsBirthDate,omitempty"`
	// True if the document contains passport numbers.
	ContainsPassportNumber bool `json:"ContainsPassportNumber,omitempty"`
	// True if the document contains drivers license numbers.
	ContainsDriversLicense bool `json:"ContainsDriversLicense,omitempty"`
	// True if the document contains social security numbers.
	ContainsSocialSecurityNumber bool `json:"ContainsSocialSecurityNumber,omitempty"`
	// True if the document contains taxpayer IDs.
	ContainsTaxpayerID bool `json:"ContainsTaxpayerID,omitempty"`
	// True if the document contains credit card numbers.
	ContainsCreditCardNumber bool `json:"ContainsCreditCardNumber,omitempty"`
	// True if the document contains credit card expiration dates.
	ContainsCreditCardExpirationDate bool `json:"ContainsCreditCardExpirationDate,omitempty"`
	// True if the document contains credit card verification codes.
	ContainsCreditCardVerificationCode bool `json:"ContainsCreditCardVerificationCode,omitempty"`
	// True if the document contains bank account numbers.
	ContainsBankAccountNumber bool `json:"ContainsBankAccountNumber,omitempty"`
	// True if the document contains IBANs.
	ContainsIBAN bool `json:"ContainsIBAN,omitempty"`
	// True if the document contains health insurance numbers.
	ContainsHealthInsuranceNumber bool `json:"ContainsHealthInsuranceNumber,omitempty"`
	// True if the document contains bearer tokens.
	ContainsBearerToken bool `json:"ContainsBearerToken,omitempty"`
	// True if the document contains HTTP cookies.
	ContainsHttpCookie bool `json:"ContainsHttpCookie,omitempty"`
	// True if the document contains private keys.
	ContainsPrivateKeys bool `json:"ContainsPrivateKeys,omitempty"`
	// True if the document contains credentials (usernames/passwords).
	ContainsCredentials bool `json:"ContainsCredentials,omitempty"`
	// True if the document contains deep web URLs (.onion).
	ContainsDeepWebUrls bool `json:"ContainsDeepWebUrls,omitempty"`
	// True if the document contains source code.
	ContainsSourceCode bool `json:"ContainsSourceCode,omitempty"`
	// True if the document contains IP addresses.
	ContainsIpAddress bool `json:"ContainsIpAddress,omitempty"`
	// True if the document contains MAC addresses.
	ContainsMacAddress bool `json:"ContainsMacAddress,omitempty"`
	// List of pages that were redacted (had PII regions blurred).
	PagesRedacted []RedactedPageInfo `json:"PagesRedacted,omitempty"`
}
