/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Information about a redacted page.
type RedactedPageInfo struct {
	// 1-based page number that was redacted.
	PageNumber int32 `json:"PageNumber,omitempty"`
}
