/*
 * dlpapi
 *
 * Easily and directly scan and detect sensitive data (PII) in input text.
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package Go-CloudmersiveDlpApiClient

// Response object for advanced DLP text redaction with 34 PII detection results, redacted text, and optional rationale.
type DlpAdvancedRedactionResponse struct {
	// The redacted text with PII removed or replaced, or the original text if no disallowed PII was found.
	RedactedText string `json:"RedactedText,omitempty"`
	// True if no disallowed PII or sensitive data types were detected; false if any disallowed type was found and redacted.
	CleanResult bool `json:"CleanResult,omitempty"`
	// True if the input contains email addresses.
	ContainsEmailAddress bool `json:"ContainsEmailAddress,omitempty"`
	// True if the input contains phone numbers.
	ContainsPhoneNumber bool `json:"ContainsPhoneNumber,omitempty"`
	// True if the input contains street addresses.
	ContainsStreetAddress bool `json:"ContainsStreetAddress,omitempty"`
	// True if the input contains person names.
	ContainsPersonName bool `json:"ContainsPersonName,omitempty"`
	// True if the input contains birth dates.
	ContainsBirthDate bool `json:"ContainsBirthDate,omitempty"`
	// True if the input contains passport numbers.
	ContainsPassportNumber bool `json:"ContainsPassportNumber,omitempty"`
	// True if the input contains drivers license numbers.
	ContainsDriversLicense bool `json:"ContainsDriversLicense,omitempty"`
	// True if the input contains social security numbers.
	ContainsSocialSecurityNumber bool `json:"ContainsSocialSecurityNumber,omitempty"`
	// True if the input contains taxpayer IDs.
	ContainsTaxpayerID bool `json:"ContainsTaxpayerID,omitempty"`
	// True if the input contains credit card numbers.
	ContainsCreditCardNumber bool `json:"ContainsCreditCardNumber,omitempty"`
	// True if the input contains credit card expiration dates.
	ContainsCreditCardExpirationDate bool `json:"ContainsCreditCardExpirationDate,omitempty"`
	// True if the input contains credit card verification codes.
	ContainsCreditCardVerificationCode bool `json:"ContainsCreditCardVerificationCode,omitempty"`
	// True if the input contains bank account numbers.
	ContainsBankAccountNumber bool `json:"ContainsBankAccountNumber,omitempty"`
	// True if the input contains IBANs.
	ContainsIBAN bool `json:"ContainsIBAN,omitempty"`
	// True if the input contains health insurance numbers.
	ContainsHealthInsuranceNumber bool `json:"ContainsHealthInsuranceNumber,omitempty"`
	// True if the input contains bearer tokens.
	ContainsBearerToken bool `json:"ContainsBearerToken,omitempty"`
	// True if the input contains HTTP cookies.
	ContainsHttpCookie bool `json:"ContainsHttpCookie,omitempty"`
	// True if the input contains private keys.
	ContainsPrivateKeys bool `json:"ContainsPrivateKeys,omitempty"`
	// True if the input contains credentials (usernames/passwords).
	ContainsCredentials bool `json:"ContainsCredentials,omitempty"`
	// True if the input contains deep web URLs (.onion).
	ContainsDeepWebUrls bool `json:"ContainsDeepWebUrls,omitempty"`
	// True if the input contains source code.
	ContainsSourceCode bool `json:"ContainsSourceCode,omitempty"`
	// True if the input contains IP addresses.
	ContainsIpAddress bool `json:"ContainsIpAddress,omitempty"`
	// True if the input contains MAC addresses.
	ContainsMacAddress bool `json:"ContainsMacAddress,omitempty"`
	// True if the input contains health insurance member IDs.
	ContainsHealthInsuranceMemberID bool `json:"ContainsHealthInsuranceMemberID,omitempty"`
	// True if the input contains references to injuries or diseases.
	ContainsHealthInjuryOrDisease bool `json:"ContainsHealthInjuryOrDisease,omitempty"`
	// True if the input contains references to types of medical treatment.
	ContainsHealthTypeOfTreatment bool `json:"ContainsHealthTypeOfTreatment,omitempty"`
	// True if the input contains dates and times of medical treatment.
	ContainsHealthDateAndTimeOfTreatment bool `json:"ContainsHealthDateAndTimeOfTreatment,omitempty"`
	// True if the input contains health plan beneficiary numbers.
	ContainsHealthPlanBeneficiaryNumber bool `json:"ContainsHealthPlanBeneficiaryNumber,omitempty"`
	// True if the input contains payments made for medical treatment.
	ContainsHealthPaymentsMadeForTreatment bool `json:"ContainsHealthPaymentsMadeForTreatment,omitempty"`
	// True if the input contains vehicle identifiers (e.g. license plates, VINs).
	ContainsVehicleID bool `json:"ContainsVehicleID,omitempty"`
	// True if the input contains device identifiers (e.g. serial numbers, IMEIs, MAC-level device IDs).
	ContainsDeviceID bool `json:"ContainsDeviceID,omitempty"`
	// True if the input contains names of relatives.
	ContainsNamesOfRelatives bool `json:"ContainsNamesOfRelatives,omitempty"`
	// True if the input contains health universal record locators (URLs).
	ContainsHealthUniversalRecordLocator bool `json:"ContainsHealthUniversalRecordLocator,omitempty"`
	// True if the input contains biometric data references (e.g. fingerprints, retinal scans, voiceprints).
	ContainsBiometrics bool `json:"ContainsBiometrics,omitempty"`
	// Rationale for why the conclusion was formed. Only populated when ProvideAnalysisRationale is set to true in the request.
	AnalysisRationale string `json:"AnalysisRationale,omitempty"`
}
